package com.waitlist.service;

import com.waitlist.exception.ResourceNotFoundException;
import com.waitlist.model.Entry;
import com.waitlist.model.EntrySource;
import com.waitlist.model.EventName;
import com.waitlist.dto.EntryDTO;
import com.waitlist.repository.EntryRepository;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class EntryService {

    private static final Logger logger = LoggerFactory.getLogger(EntryService.class);

    @Autowired
    private EntryRepository entryRepository;


    @Autowired
    private NotificationService notificationService;

    @Autowired
    private SmsService smsService;

    @Autowired
    private org.springframework.core.env.Environment environment;

    @org.springframework.beans.factory.annotation.Value("${twilio.dev-target:}")
    private String devTarget;

    @org.springframework.beans.factory.annotation.Value("${twilio.use-dev-number:false}")
    private boolean useDevNumber;

    /**
     * Estimate total wait time (minutes) based on current queue.
     * 5 minutes allocated for each party under 4 people, 10 minutes otherwise.
     * @param object 
     */
    public int calculateEstimatedWaitMinutes(List<Entry> list) {
        int minutes = 0;
        for (Entry e : list) {
            if (e.getPartySize() < 4) {
                minutes += 5;
            } else {
                minutes += 10;
            }
        }
        return minutes;
    }

    /**
     * Set every active entry to inactive.  This is used when the waitlist is
     * closed (either by flag or by elapsed close time) so that the frontend no
     * longer sees any items and the history is preserved with an inactive mark.
     */
    @org.springframework.transaction.annotation.Transactional
    public void deactivateAllEntries() {
        entryRepository.deactivateAll();
    }

    @Autowired
    @org.springframework.context.annotation.Lazy
    private AccountService accountService;

    public Entry create(String code, Entry entry) {
        if (!accountService.isWaitlistOpen(accountService.getAccountByCode(code).getId())) {
            throw new com.waitlist.exception.WaitlistDisabledException();
        }

        // id will be generated by the database. clear any client-provided value
        entry.setId(null);
        entry.setAccount(accountService.getAccountByCode(code));
        if (entry.getSource() == null) {
            entry.setSource(EntrySource.WEB);
        }
        Entry saved = entryRepository.save(entry);
        
        Map<String, Object> notificationResponse = notificationService.sendFormattedNotification(entry, EventName.NEW_ENTRY);
        if (notificationResponse.get("success") instanceof Boolean && !(Boolean) notificationResponse.get("success")) {
            logger.warn("Failed to send notification for new entry {}: {}", saved.getId(), notificationResponse.get("message"));
        }

        return saved;
    }
    
    /**
     * Delete an entry from the waitlist.
     */
    public Entry deleteEntry(String code) {
        Entry entry = resolve(code);
        entry.setActive(false);
        Entry saved = entryRepository.save(entry);    
        return saved;
    }

    /**
     * Mark entry as called/arrived status.
     */
    public Entry markCalled(String code, boolean called) {
        Entry entry = resolve(code);
        entry.setCalled(called);
        return entryRepository.save(entry);
    }

    public Entry getById(Long id) {
        return entryRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Entry not found: " + id));
    }

    /**
     * Send an arbitrary SMS message to the phone number on the entry.
     * If no number is present nothing will happen.
     */
    public void sendSmsToEntry(String code, String message) {
        Entry entry = resolve(code);
        if (entry.getPhone() == null || entry.getPhone().isBlank()) {
            return;
        }
        String to = entry.getPhone();
        // optionally override target if we're in dev and the feature flag is set
        if (isDevProfile() && useDevNumber && devTarget != null && !devTarget.isBlank()) {
            to = devTarget;
        }
        smsService.sendSms(accountService.getAccountByCode(entry.getAccount().getCode()).getId(), to, message);
    }

    private boolean isDevProfile() {
        if (environment == null) return false;
        for (String profile : environment.getActiveProfiles()) {
            if ("dev".equals(profile)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Lookup an entry either by code.
     */
    public Entry resolve(String code) {
        if (code == null) {
            throw new ResourceNotFoundException("Entry identifier is null");
        }
        return entryRepository.findByCodeAndActiveTrue(code)
                .orElseThrow(() -> new ResourceNotFoundException("Entry not found: " + code));
    }

    public Entry resolveFailOk(String code) {
        if (code == null) {
            return null;
        }
        return entryRepository.findByCodeAndActiveTrue(code).orElse(null);
    }

    public List<Entry> getAllActiveEntriesForAccount(Long accountId) {
        List<Entry> entries = entryRepository.findAllByAccountIdAndActiveTrueAndCalledFalse(accountId);
        return entries;
    }

    /**
     * Return a list of DTOs for the account's active entries.
     */
    public List<EntryDTO> getAllActiveEntryDtosForAccount(Long accountId) {
        return getAllActiveEntriesForAccount(accountId).stream().filter(e -> !e.isCalled())
                .map(this::toDto)
                .collect(Collectors.toList());
    }

    /**
     * Map an entity to its DTO representation with only accountId.
     */
    public EntryDTO toDto(Entry entry) {
        if (entry == null) return null;
        EntryDTO dto = new EntryDTO();
        dto.setId(entry.getId());
        dto.setCode(entry.getCode());
        dto.setAccountId(entry.getAccount() != null ? entry.getAccount().getId() : null);
        dto.setName(entry.getName());
        dto.setPhone(entry.getPhone());
        dto.setPartySize(entry.getPartySize());
        dto.setTimestamp(entry.getTimestamp());
        dto.setCalled(entry.isCalled());
        dto.setActive(entry.isActive());
        dto.setSource(entry.getSource());
        return dto;
    }
}
