package com.waitlist.service;

import com.twilio.exception.ApiException;
import com.waitlist.exception.ResourceNotFoundException;
import com.waitlist.model.Entry;
import com.waitlist.dto.EntryDTO;
import com.waitlist.repository.EntryRepository;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class EntryService {

    private static final Logger logger = LoggerFactory.getLogger(EntryService.class);
    
    @Autowired
    private EntryRepository entryRepository;


    @Autowired
    private SmsService smsService;

    @Autowired
    private org.springframework.core.env.Environment environment;

    @org.springframework.beans.factory.annotation.Value("${twilio.dev-target:}")
    private String devTarget;

    @org.springframework.beans.factory.annotation.Value("${twilio.use-dev-number:false}")
    private boolean useDevNumber;

    // base URL for the frontend application, used in SMS templates
    @org.springframework.beans.factory.annotation.Value("${app.frontend.url:http://localhost:5173}")
    private String frontendUrl;

    /**
     * Estimate total wait time (minutes) based on current queue.
     * 5 minutes allocated for each party under 4 people, 10 minutes otherwise.
     * @param object 
     */
    public int calculateEstimatedWaitMinutes(List<Entry> list) {
        int minutes = 0;
        for (Entry e : list) {
            if (e.getPartySize() < 4) {
                minutes += 5;
            } else {
                minutes += 10;
            }
        }
        return minutes;
    }

    /**
     * Set every active entry to inactive.  This is used when the waitlist is
     * closed (either by flag or by elapsed close time) so that the frontend no
     * longer sees any items and the history is preserved with an inactive mark.
     */
    @org.springframework.transaction.annotation.Transactional
    public void deactivateAllEntries() {
        entryRepository.deactivateAll();
    }

    @Autowired
    @org.springframework.context.annotation.Lazy
    private AccountService accountService;

    public Entry create(String code, Entry entry) {
        // ensure the waitlist is currently enabled/open; use primary account (id=1)
        if (!accountService.isWaitlistOpen(accountService.getAccountByCode(code).getId())) {
            throw new com.waitlist.exception.WaitlistDisabledException();
        }

        // id will be generated by the database. clear any client-provided value
        entry.setId(null);
        entry.setAccount(accountService.getAccountByCode(code));
        Entry saved = entryRepository.save(entry);
        if (entry.getAccount().isSmsEnabled() && entry.getAccount().getTwilioAccountSid() != null && entry.getAccount().getTwilioAuthToken() != null) {
            notifyOfTableSms(entry, code, MessageTemplate.NEW_ENTRY);
        } 
        return saved;
        
    }

    public void notifyOfTableSms(Entry entry, String entryCode, MessageTemplate templateType) {
        if (entry == null) {
            try {
                entry = resolve(entryCode);
            } catch (ResourceNotFoundException e) {
                throw new ResourceNotFoundException("Cannot send notification: entry not found for code " + entryCode);
            }
        }
        long accountId = entry.getAccount().getId();
        if (!accountService.isWaitlistOpen(accountId)) {
            throw new com.waitlist.exception.WaitlistDisabledException();
        }

        try {
            if (entry.getPhone() != null && !entry.getPhone().isBlank()) {
                String to = entry.getPhone();
                if (isDevProfile() && useDevNumber && devTarget != null && !devTarget.isBlank()) {
                    to = devTarget;
                }
                String template = accountService.getMessageTemplate(accountId, templateType.getKey());
                if (template == null) {
                    template = templateType.getDefaultTemplate();
                }
                switch (templateType.getKey()) {
                    case "tableReady":
                        String tableReadyMsgString = String.format(template,
                        entry.getName(),
                        entry.getName(),
                        entry.getPhone(),
                        entry.getPartySize());
                        smsService.sendSms(accountId, to, tableReadyMsgString);
                        break;
                    case "newEntry":
                        String newEntryMsgString = String.format(template,
                        entry.getName(),
                        frontendUrl + "/waitlist/view",
                        entry.getCode(),
                        entry.getName(),
                        entry.getPhone(),
                        entry.getPartySize());
                        smsService.sendSms(accountId, to, newEntryMsgString);
                        break;
                    default:
                        logger.warn("Unknown message template type: {}", templateType.getKey());
                }
            }
        } catch (ApiException e) {
            logger.error("Failed to send SMS notification for table ready: {}", e.getMessage());
        }
    }

    /**
     * Delete an entry from the waitlist.
     */
    /**
     * Delete an entry from the waitlist by numeric id or public code.
     * Returns the modified entity so callers can inspect its code if needed.
     */
    public Entry deleteEntry(String idOrCode) {
        Entry entry = resolve(idOrCode);
        // log a prominent message whenever an entry is deactivated/deleted
        logger.info("========== DELETING ENTRY ==========");
        logger.info("Entry identified for deletion: id={}, code={}, name={} partySize={} active={}",
                entry.getId(), entry.getCode(), entry.getName(), entry.getPartySize(), entry.isActive());
        entry.setActive(false);
        Entry saved = entryRepository.save(entry);
        logger.info("Entry marked inactive and saved: id={}, code={}", saved.getId(), saved.getCode());
        logger.info("====================================");
        return saved;
    }

    /**
     * Mark entry as called/arrived status.
     */
    public Entry markCalled(String idOrCode, boolean called) {
        Entry entry = resolve(idOrCode);
        entry.setCalled(called);
        return entryRepository.save(entry);
    }

    public Entry getById(Long id) {
        return entryRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Entry not found: " + id));
    }

    /**
     * Send an arbitrary SMS message to the phone number on the entry.
     * If no number is present nothing will happen.
     */
    public void sendSmsToEntry(String code, String message) {
        Entry entry = resolve(code);
        if (entry.getPhone() == null || entry.getPhone().isBlank()) {
            return;
        }
        String to = entry.getPhone();
        // optionally override target if we're in dev and the feature flag is set
        if (isDevProfile() && useDevNumber && devTarget != null && !devTarget.isBlank()) {
            to = devTarget;
        }
        smsService.sendSms(accountService.getAccountByCode(entry.getAccount().getCode()).getId(), to, message);
    }

    private boolean isDevProfile() {
        if (environment == null) return false;
        for (String profile : environment.getActiveProfiles()) {
            if ("dev".equals(profile)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Lookup an entry either by numeric ID or by public code.
     */
    public Entry resolve(String code) {
        if (code == null) {
            throw new ResourceNotFoundException("Entry identifier is null");
        }
        // not a number, look up by code
        return entryRepository.findByCodeAndActiveTrue(code)
                .orElseThrow(() -> new ResourceNotFoundException("Entry not found: " + code));
    }

    public List<Entry> getAllActiveEntriesForAccount(Long accountId) {
        List<Entry> entries = entryRepository.findAllByAccountIdAndActiveTrue(accountId);
        return entries;
    }

    /**
     * Return a list of DTOs for the account's active entries.
     */
    public List<EntryDTO> getAllActiveEntryDtosForAccount(Long accountId) {
        return getAllActiveEntriesForAccount(accountId).stream()
                .map(this::toDto)
                .collect(Collectors.toList());
    }

    /**
     * Map an entity to its DTO representation with only accountId.
     */
    public EntryDTO toDto(Entry entry) {
        if (entry == null) return null;
        EntryDTO dto = new EntryDTO();
        dto.setId(entry.getId());
        dto.setCode(entry.getCode());
        dto.setAccountId(entry.getAccount() != null ? entry.getAccount().getId() : null);
        dto.setName(entry.getName());
        dto.setPhone(entry.getPhone());
        dto.setPartySize(entry.getPartySize());
        dto.setTimestamp(entry.getTimestamp());
        dto.setCalled(entry.isCalled());
        dto.setActive(entry.isActive());
        dto.setSource(entry.getSource());
        return dto;
    }
}
