package com.waitlist.service;

import com.twilio.exception.ApiException;
import com.waitlist.exception.ResourceNotFoundException;
import com.waitlist.model.Entry;
import com.waitlist.repository.EntryRepository;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class EntryService {

    private static final Logger logger = LoggerFactory.getLogger(EntryService.class);
    
    @Autowired
    private EntryRepository entryRepository;


    @Autowired
    private SmsService smsService;

    @Autowired
    private org.springframework.core.env.Environment environment;

    @org.springframework.beans.factory.annotation.Value("${twilio.dev-target:}")
    private String devTarget;

    @org.springframework.beans.factory.annotation.Value("${twilio.use-dev-number:false}")
    private boolean useDevNumber;

    public List<Entry> getAll() {
        return entryRepository.findByActiveTrueOrderByTimestampAsc();
    }

    /**
     * Estimate total wait time (minutes) based on current queue.
     * 5 minutes allocated for each party under 4 people, 10 minutes otherwise.
     */
    public int calculateEstimatedWaitMinutes() {
        List<Entry> list = getAll();
        int minutes = 0;
        for (Entry e : list) {
            if (e.getPartySize() < 4) {
                minutes += 5;
            } else {
                minutes += 10;
            }
        }
        return minutes;
    }

    /**
     * Set every active entry to inactive.  This is used when the waitlist is
     * closed (either by flag or by elapsed close time) so that the frontend no
     * longer sees any items and the history is preserved with an inactive mark.
     */
    @org.springframework.transaction.annotation.Transactional
    public void deactivateAllEntries() {
        entryRepository.deactivateAll();
    }

    @Autowired
    @org.springframework.context.annotation.Lazy
    private AccountService accountService;

    public Entry create(Entry entry) {
        // ensure the waitlist is currently enabled/open; use primary account (id=1)
        if (!accountService.isWaitlistOpen(1L)) {
            throw new com.waitlist.exception.WaitlistDisabledException();
        }

        // id will be generated by the database. clear any client-provided value
        entry.setId(null);
        Entry saved = entryRepository.save(entry);
        notifyOfTableSms(entry, entry.getCode(), MessageTemplate.NEW_ENTRY);
        return saved;
    }

    public void notifyOfTableSms(Entry entry, String idOrCode, MessageTemplate templateType) {
        // ensure the waitlist is currently enabled/open; use primary account (id=1)
        if (!accountService.isWaitlistOpen(1L)) {
            throw new com.waitlist.exception.WaitlistDisabledException();
        }
        if (entry == null) {
            entry = resolve(idOrCode);
        }
        try {
            if (entry.getPhone() != null && !entry.getPhone().isBlank()) {
                String to = entry.getPhone();
                if (isDevProfile() && useDevNumber && devTarget != null && !devTarget.isBlank()) {
                    to = devTarget;
                }
                String template = accountService.getMessageTemplate(1L, templateType.getKey());
                switch (templateType.getKey()) {
                    case "tableReady":
                        String tableReadyMsgString = String.format(template,
                        entry.getName(),
                        entry.getName(),
                        entry.getPhone(),
                        entry.getPartySize());
                        smsService.sendSms(1L, to, tableReadyMsgString);
                        break;
                    case "newEntry":
                        String newEntryMsgString = String.format(template,
                        entry.getName(),
                        "http://localhost:5173/waitlist",
                        entry.getCode(),
                        entry.getName(),
                        entry.getPhone(),
                        entry.getPartySize());
                        smsService.sendSms(1L, to, newEntryMsgString);
                        break;
                    default:
                        logger.warn("Unknown message template type: {}", templateType.getKey());
                }
            }
        } catch (ApiException e) {
            logger.error("Failed to send SMS notification for table ready: {}", e.getMessage());
        }
    }

    /**
     * Delete an entry from the waitlist.
     */
    /**
     * Delete an entry from the waitlist by numeric id or public code.
     * Returns the modified entity so callers can inspect its code if needed.
     */
    public Entry deleteEntry(String idOrCode) {
        Entry entry = resolve(idOrCode);
        entry.setActive(false);
        return entryRepository.save(entry);
    }

    /**
     * Mark entry as called/arrived status.
     */
    public Entry markCalled(String idOrCode, boolean called) {
        Entry entry = resolve(idOrCode);
        entry.setCalled(called);
        return entryRepository.save(entry);
    }

    public Entry getById(Long id) {
        return entryRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Entry not found: " + id));
    }

    /**
     * Send an arbitrary SMS message to the phone number on the entry.
     * If no number is present nothing will happen.
     */
    public void sendSmsToEntry(String idOrCode, String message) {
        Entry entry = resolve(idOrCode);
        if (entry.getPhone() == null || entry.getPhone().isBlank()) {
            return;
        }
        String to = entry.getPhone();
        // optionally override target if we're in dev and the feature flag is set
        if (isDevProfile() && useDevNumber && devTarget != null && !devTarget.isBlank()) {
            to = devTarget;
        }
        smsService.sendSms(1L, to, message);
    }

    private boolean isDevProfile() {
        if (environment == null) return false;
        for (String profile : environment.getActiveProfiles()) {
            if ("dev".equals(profile)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Lookup an entry either by numeric ID or by public code.
     */
    private Entry resolve(String idOrCode) {
        if (idOrCode == null) {
            throw new ResourceNotFoundException("Entry identifier is null");
        }
        // try numeric parse first
        try {
            long id = Long.parseLong(idOrCode);
            return getById(id);
        } catch (NumberFormatException e) {
            // not a number, look up by code
            return entryRepository.findByCodeAndActiveTrue(idOrCode)
                    .orElseThrow(() -> new ResourceNotFoundException("Entry not found: " + idOrCode));
        }
    }

}
