-- Ensure entries.id is automatically generated by the database.
-- The original migration created a plain BIGINT primary key with no default
-- so inserts from JPA were failing with NULL values.

-- create a sequence and attach it to the column
CREATE SEQUENCE IF NOT EXISTS entries_id_seq;
ALTER TABLE entries
    ALTER COLUMN id SET DEFAULT nextval('entries_id_seq');

-- make sure the sequence value starts past any existing rows
SELECT setval('entries_id_seq', COALESCE((SELECT MAX(id) FROM entries),1));

ALTER SEQUENCE entries_id_seq OWNED BY entries.id;
